FROM nginx

COPY nginx/default.conf /etc/nginx/conf.d/default.conf

#docker run --name nginx-server-ershi -d -p 80:80 --link php56fpm:phpfpm --link mysql:mysql -v g:/Projects/ershi:/app --volumes-from php56fpm nginx-server
